server.port=${PORT:8080}

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://ballast.proxy.rlwy.net:28672/railway}
spring.datasource.username=${PGUSER:postgres}
spring.datasource.password=${PGPASSWORD:SUA_SENHA}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

spring.security.user.name=admin
spring.security.user.password=admin